name: pos
description: "A new Flutter project."

publish_to: "none"

version: 1.0.6+6

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.8
  shadcn_ui: ^0.26.3
  flutter_animate: ^4.5.2
  flutter_svg: ^2.1.0
  # State
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_hooks: ^0.21.2
  get_it: ^8.0.3
  event_bus: ^2.0.1
  # DB
  shared_preferences: ^2.5.3
  shared_preferences_annotation: ^0.1.1
  # Utils
  go_router: ^15.0.0
  fpdart: ^1.1.1
  collection: ^1.19.1
  # intl: ^0.19.0
  intl: ^0.20.2
  slang: ^4.7.1
  slang_flutter: ^4.7.0
  file_picker: ^10.1.2
  open_filex: ^4.7.0
  url_launcher: ^6.3.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  google_fonts: ^6.2.1
  recase: ^4.1.0
  universal_image: ^1.0.9
  appwrite: ^15.0.1
  gap: ^3.0.1
  image_picker: ^1.1.2
  bcrypt: ^1.1.3
  crypto: ^3.0.6
  syncfusion_flutter_datagrid: ^29.1.39
  syncfusion_flutter_core: ^29.1.39
  sliver_tools: ^0.2.12
  nanoid2: ^2.0.1
  pdf: ^3.11.3
  file_saver: ^0.2.14
  printing: ^5.14.2
  path_provider: ^2.1.5
  universal_html: ^2.2.4
  fl_chart: ^1.0.0
  embed_annotation: ^1.2.2
  navigator_resizable: ^1.0.2
  timeago: ^3.7.1
  syncfusion_flutter_charts: ^29.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  slang_build_runner: ^4.7.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  embed: ^1.4.1
  # shared_preferences_gen: ^0.1.1

dependency_overrides:
  analyzer: 7.3.0
  analyzer_plugin: 0.12.0
  custom_lint_visitor: 1.0.0+7.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/svg/

flutter_gen:
  output: lib/_core/strings/
  line_length: 120
  integrations:
    flutter_svg: true
    lottie: true

# appwrite
secret API key:
account:
  name: ahnaf
  email: ahnafsakil9@gmail.com
  password: 12341234
