// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'app_const.dart';

// **************************************************************************
// LiteralEmbeddingGenerator
// **************************************************************************

const _$pub = (
  name: "pos",
  description: "A new Flutter project.",
  publishTo: "none",
  version: "1.0.5+5",
  environment: (sdk: "^3.8.0"),
  dependencies: (
    flutter: (sdk: "flutter"),
    flutterLocalizations: (sdk: "flutter"),
    flutterWebPlugins: (sdk: "flutter"),
    cupertinoIcons: "^1.0.8",
    shadcnUi: "^0.26.3",
    flutterAnimate: "^4.5.2",
    flutterSvg: "^2.1.0",
    hooksRiverpod: "^2.6.1",
    riverpodAnnotation: "^2.6.1",
    flutterHooks: "^0.21.2",
    getIt: "^8.0.3",
    eventBus: "^2.0.1",
    sharedPreferences: "^2.5.3",
    sharedPreferencesAnnotation: "^0.1.1",
    goRouter: "^15.0.0",
    fpdart: "^1.1.1",
    collection: "^1.19.1",
    intl: "^0.20.2",
    slang: "^4.7.1",
    slangFlutter: "^4.7.0",
    filePicker: "^10.1.2",
    openFilex: "^4.7.0",
    urlLauncher: "^6.3.1",
    flutterFormBuilder: "^10.0.1",
    formBuilderValidators: "^11.1.2",
    googleFonts: "^6.2.1",
    recase: "^4.1.0",
    universalImage: "^1.0.9",
    appwrite: "^15.0.1",
    gap: "^3.0.1",
    imagePicker: "^1.1.2",
    bcrypt: "^1.1.3",
    crypto: "^3.0.6",
    syncfusionFlutterDatagrid: "^29.1.39",
    syncfusionFlutterCore: "^29.1.39",
    sliverTools: "^0.2.12",
    nanoid2: "^2.0.1",
    pdf: "^3.11.3",
    fileSaver: "^0.2.14",
    printing: "^5.14.2",
    pathProvider: "^2.1.5",
    universalHtml: "^2.2.4",
    flChart: "^1.0.0",
    embedAnnotation: "^1.2.2",
    navigatorResizable: "^1.0.2",
  ),
  devDependencies: (
    flutterTest: (sdk: "flutter"),
    flutterLints: "^5.0.0",
    slangBuildRunner: "^4.7.0",
    customLint: "^0.7.5",
    riverpodLint: "^2.6.5",
    riverpodGenerator: "^2.6.5",
    buildRunner: "^2.4.15",
    embed: "^1.4.1",
  ),
  dependencyOverrides: (
    analyzer: "7.3.0",
    analyzerPlugin: "0.12.0",
    customLintVisitor: "1.0.0+7.3.0",
  ),
  flutter: (usesMaterialDesign: true, assets: ["assets/icons/", "assets/svg/"]),
  flutterGen: (
    output: "lib/_core/strings/",
    lineLength: 120,
    integrations: (flutterSvg: true, lottie: true),
  ),
  secretAPIKey: null,
  account: (name: "ahnaf", email: "ahnafsakil9@gmail.com", password: 12341234),
);
